import { ImportModuleConfig } from "@/types/import";

/**
 * Comprehensive list of available importable modules for the Central Import System.
 * Automatically mapped to Prisma schema models with maximum user-importable fields.
 * Excludes auto-generated system fields (id, createdAt, updatedAt, createdBy, chartOfAccountId, etc.).
 */
export const IMPORT_MODULES: ImportModuleConfig[] = [
  {
    id: "Client",
    name: "Client",
    label: "Clients / Customers",
    description: "Import client profiles with loyalty program and automated Accounts Receivable sub-ledger accounts.",
    targetModel: "Client",
    permissionKey: "peoples.clients",
    uniqueIdentifierKeys: ["email", "clientCode", "membershipNumber"],
    fields: [
      { key: "name", label: "Client Name", type: "string", required: true, description: "Full client or business owner name", example: "Dhaka Outfitters" },
      { key: "clientCode", label: "Client Code / Customer ID", type: "string", required: false, description: "Customer ID (Auto-generated CLI1000001 if empty)", example: "CLI1000001" },
      { key: "email", label: "Email Address", type: "email", required: false, description: "Client email address", example: "info@dhakaoutfitters.com" },
      { key: "phone", label: "Phone Number", type: "phone", required: false, description: "Contact phone number", example: "01711223344" },
      { key: "company", label: "Company Name", type: "string", required: false, description: "Organization or store name", example: "Dhaka Outfitters Ltd" },
      { key: "address", label: "Address", type: "string", required: false, description: "Street address", example: "House 45, Road 11, Banani" },
      { key: "city", label: "City", type: "string", required: false, description: "City name", example: "Dhaka" },
      { key: "state", label: "State / Division", type: "string", required: false, description: "State or division name", example: "Dhaka" },
      { key: "zip", label: "ZIP / Postal Code", type: "string", required: false, description: "Postal code", example: "1213" },
      { key: "country", label: "Country", type: "string", required: false, description: "Country name", example: "Bangladesh" },
      { key: "image", label: "Client Photo / Logo URL", type: "string", required: false, description: "Avatar or image URL", example: "https://example.com/client.jpg" },
      { key: "clientType", label: "Client Type", type: "enum", required: false, enumValues: ["regular", "wholesale"], description: "Customer classification", example: "wholesale" },
      { key: "openingBalance", label: "Opening Balance", type: "number", required: false, description: "Initial AR debit balance", example: "10000.00" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Account status", example: "active" },
      { key: "membershipNumber", label: "Membership Number", type: "string", required: false, description: "Loyalty card number (defaults to Client Code)", example: "CLI1000001" },
      { key: "membershipTier", label: "Membership Tier", type: "enum", required: false, enumValues: ["NONE", "BRONZE", "SILVER", "GOLD", "PLATINUM"], description: "Loyalty tier status", example: "SILVER" },
      { key: "membershipStatus", label: "Membership Status", type: "enum", required: false, enumValues: ["ACTIVE", "INACTIVE", "EXPIRED"], description: "Loyalty account status", example: "ACTIVE" },
      { key: "membershipPoints", label: "Membership Loyalty Points", type: "number", required: false, description: "Loyalty reward points balance", example: "150" },
      { key: "membershipExpiry", label: "Membership Expiry Date", type: "date", required: false, description: "Loyalty expiration date (YYYY-MM-DD)", example: "2026-12-31" },
    ],
    sampleData: {
      "Client Name": "Dhaka Outfitters",
      "Client Code / Customer ID": "CLI1000001",
      "Email Address": "info@dhakaoutfitters.com",
      "Phone Number": "01711223344",
      "Company Name": "Dhaka Outfitters Ltd",
      "Address": "House 45, Road 11, Banani",
      "City": "Dhaka",
      "State / Division": "Dhaka",
      "ZIP / Postal Code": "1213",
      "Country": "Bangladesh",
      "Client Photo / Logo URL": "https://example.com/logo.jpg",
      "Client Type": "wholesale",
      "Opening Balance": "10000.00",
      "Status": "active",
      "Membership Number": "CLI1000001",
      "Membership Tier": "SILVER",
      "Membership Status": "ACTIVE",
      "Membership Loyalty Points": "150",
      "Membership Expiry Date": "2026-12-31",
    },
  },
  {
    id: "Products",
    name: "Products",
    label: "Products / Items",
    description: "Import products and inventory item master records with pricing, barcodes, and specs.",
    targetModel: "Item",
    permissionKey: "master.items",
    uniqueIdentifierKeys: ["code", "barcode", "name"],
    fields: [
      { key: "name", label: "Item Name", type: "string", required: true, description: "Name of the product/item", example: "Cotton Crew T-Shirt" },
      { key: "code", label: "Item Code / SKU", type: "string", required: false, description: "Unique code or SKU (Auto-generated if empty)", example: "ITM-1001" },
      { key: "salesPrice", label: "Sales Price", type: "number", required: true, description: "Selling price per unit", example: "499.00" },
      { key: "costPrice", label: "Purchase / Cost Price", type: "number", required: false, description: "Cost price per unit", example: "250.00" },
      { key: "wholesalePrice", label: "Wholesale Price", type: "number", required: false, description: "Bulk wholesale price", example: "400.00" },
      { key: "wholesaleDiscountAmount", label: "Wholesale Discount Amount", type: "number", required: false, description: "Wholesale flat discount", example: "50.00" },
      { key: "discount", label: "Retail Discount Amount", type: "number", required: false, description: "Retail discount amount", example: "20.00" },
      { key: "description", label: "Description", type: "string", required: false, description: "Detailed item description", example: "100% Organic Cotton T-Shirt" },
      { key: "categoryName", label: "Category Name", type: "string", required: false, description: "Category name to link", example: "Apparel" },
      { key: "brandName", label: "Brand Name", type: "string", required: false, description: "Brand name to link", example: "EcoStyle" },
      { key: "unitCode", label: "Unit Symbol", type: "string", required: false, description: "Unit symbol (e.g., PCS, KG, BOX)", example: "PCS" },
      { key: "barcode", label: "Barcode / EAN", type: "string", required: false, description: "Product barcode number", example: "8941234567890" },
      { key: "fit", label: "Garment Fit Spec", type: "string", required: false, description: "Fit spec (e.g. Slim, Regular, Relaxed)", example: "Slim Fit" },
      { key: "isEnableEcom", label: "Enable E-Commerce Store", type: "boolean", required: false, description: "Publish on e-commerce store", example: "true" },
      { key: "trackInventory", label: "Track Inventory Stock", type: "boolean", required: false, description: "Enable stock level tracking", example: "true" },
      { key: "isVatEnabled", label: "Enable VAT / Tax", type: "boolean", required: false, description: "Enable tax calculation", example: "true" },
      { key: "vatPercentage", label: "VAT Percentage (%)", type: "number", required: false, description: "VAT rate percentage", example: "7.5" },
      { key: "featuredImage", label: "Featured Image URL", type: "string", required: false, description: "Primary product photo URL", example: "https://example.com/shirt.jpg" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Item catalog status", example: "active" },
    ],
    sampleData: {
      "Item Name": "Premium Cotton Polo",
      "Item Code / SKU": "POLO-001",
      "Sales Price": "850.00",
      "Purchase / Cost Price": "400.00",
      "Wholesale Price": "700.00",
      "Wholesale Discount Amount": "50.00",
      "Retail Discount Amount": "20.00",
      "Description": "High quality pique cotton polo shirt",
      "Category Name": "Apparel",
      "Brand Name": "FashionCo",
      "Unit Symbol": "PCS",
      "Barcode / EAN": "8941000022331",
      "Garment Fit Spec": "Regular Fit",
      "Enable E-Commerce Store": "true",
      "Track Inventory Stock": "true",
      "Enable VAT / Tax": "true",
      "VAT Percentage (%)": "7.5",
      "Featured Image URL": "https://example.com/polo.jpg",
      "Status": "active",
    },
  },
  {
    id: "Supplier",
    name: "Supplier",
    label: "Suppliers / Vendors",
    description: "Import vendors and suppliers with automated Accounts Payable sub-ledger account creation.",
    targetModel: "Supplier",
    permissionKey: "peoples.suppliers",
    uniqueIdentifierKeys: ["email", "supplierCode"],
    fields: [
      { key: "name", label: "Supplier Name", type: "string", required: true, description: "Vendor contact or business name", example: "Apex Fabrics" },
      { key: "supplierCode", label: "Supplier Code / Vendor ID", type: "string", required: false, description: "Vendor ID (Auto-generated SUP1000001 if empty)", example: "SUP1000001" },
      { key: "email", label: "Email Address", type: "email", required: false, description: "Supplier email address", example: "sales@apexfabrics.com" },
      { key: "phone", label: "Phone Number", type: "phone", required: false, description: "Contact phone number", example: "+8801800000000" },
      { key: "company", label: "Company Name", type: "string", required: false, description: "Vendor company name", example: "Apex Fabrics Mills" },
      { key: "address", label: "Address", type: "string", required: false, description: "Factory or office address", example: "Plot 12, EPZ Area" },
      { key: "city", label: "City", type: "string", required: false, description: "City name", example: "Chittagong" },
      { key: "state", label: "State / Division", type: "string", required: false, description: "State or division name", example: "Chittagong" },
      { key: "zip", label: "ZIP / Postal Code", type: "string", required: false, description: "Postal code", example: "4000" },
      { key: "country", label: "Country", type: "string", required: false, description: "Country name", example: "Bangladesh" },
      { key: "image", label: "Logo / Photo URL", type: "string", required: false, description: "Vendor logo URL", example: "https://example.com/supplier.jpg" },
      { key: "openingBalance", label: "Opening Balance", type: "number", required: false, description: "Initial AP credit opening balance", example: "15000.00" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Supplier status", example: "active" },
    ],
    sampleData: {
      "Supplier Name": "TexStyle Yarn Mills",
      "Supplier Code / Vendor ID": "SUP1000001",
      "Email Address": "orders@texstyle.com",
      "Phone Number": "01811998877",
      "Company Name": "TexStyle Mills Ltd",
      "Address": "Sector 7, Uttara",
      "City": "Dhaka",
      "State / Division": "Dhaka",
      "ZIP / Postal Code": "1230",
      "Country": "Bangladesh",
      "Logo / Photo URL": "https://example.com/vendor.jpg",
      "Opening Balance": "25000.00",
      "Status": "active",
    },
  },
  {
    id: "Employee",
    name: "Employee",
    label: "Employees",
    description: "Import employee personal, contact, departmental, and payroll data.",
    targetModel: "Employee",
    permissionKey: "peoples.employees",
    uniqueIdentifierKeys: ["employeeCode", "email", "nationalId"],
    fields: [
      { key: "employeeCode", label: "Employee Code / Staff ID", type: "string", required: true, description: "Unique staff ID code", example: "EMP-2025-01" },
      { key: "name", label: "Full Name", type: "string", required: true, description: "Employee full name", example: "Kamal Hossain" },
      { key: "email", label: "Email Address", type: "email", required: false, description: "Work email address", example: "kamal@company.com" },
      { key: "phone", label: "Phone Number", type: "phone", required: false, description: "Mobile phone number", example: "01712345678" },
      { key: "department", label: "Department", type: "string", required: false, description: "Department name", example: "Accounts" },
      { key: "designation", label: "Designation", type: "string", required: false, description: "Job title", example: "Senior Accountant" },
      { key: "gender", label: "Gender", type: "enum", required: false, enumValues: ["MALE", "FEMALE", "OTHER"], description: "Gender", example: "MALE" },
      { key: "bloodGroup", label: "Blood Group", type: "string", required: false, description: "Blood group type", example: "O+" },
      { key: "nationalId", label: "National ID / NID", type: "string", required: false, description: "NID or Passport number", example: "1990123456789" },
      { key: "dateOfBirth", label: "Date of Birth", type: "date", required: false, description: "Birth date (YYYY-MM-DD)", example: "1990-05-12" },
      { key: "joiningDate", label: "Joining Date", type: "date", required: false, description: "Employment start date (YYYY-MM-DD)", example: "2025-01-15" },
      { key: "salary", label: "Base Salary", type: "number", required: false, description: "Base monthly salary", example: "35000" },
      { key: "employmentType", label: "Employment Type", type: "enum", required: false, enumValues: ["PERMANENT", "PROBATION", "CONTRACTUAL", "TEMPORARY"], description: "Contract type", example: "PERMANENT" },
      { key: "type", label: "Staff Type", type: "string", required: false, description: "Staff category (e.g. Officer, Operator)", example: "Officer" },
      { key: "photo", label: "Photo URL", type: "string", required: false, description: "Staff portrait photo URL", example: "https://example.com/staff.jpg" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Employment status", example: "active" },
    ],
    sampleData: {
      "Employee Code / Staff ID": "EMP-1002",
      "Full Name": "Rahim Uddin",
      "Email Address": "rahim@company.com",
      "Phone Number": "01999887766",
      "Department": "Sales",
      "Designation": "Sales Executive",
      "Gender": "MALE",
      "Blood Group": "B+",
      "National ID / NID": "1992987654321",
      "Date of Birth": "1992-08-20",
      "Joining Date": "2025-02-01",
      "Base Salary": "45000",
      "Employment Type": "PERMANENT",
      "Staff Type": "Executive",
      "Photo URL": "https://example.com/rahim.jpg",
      "Status": "active",
    },
  },
  {
    id: "Warehouses",
    name: "Warehouses",
    label: "Warehouses / Storage",
    description: "Import warehouse storage facility records.",
    targetModel: "Warehouse",
    permissionKey: "master.warehouses",
    uniqueIdentifierKeys: ["code", "name"],
    fields: [
      { key: "name", label: "Warehouse Name", type: "string", required: true, description: "Facility name", example: "Main Central Depot" },
      { key: "code", label: "Warehouse Code", type: "string", required: false, description: "Short code identifier (Auto-generated WH-XXXX if empty)", example: "WH-01" },
      { key: "address", label: "Address", type: "string", required: false, description: "Physical location address", example: "Plot 88, Gazipur Industrial Area" },
      { key: "city", label: "City", type: "string", required: false, description: "City name", example: "Gazipur" },
      { key: "state", label: "State / Division", type: "string", required: false, description: "State or division name", example: "Dhaka" },
      { key: "zip", label: "ZIP Code", type: "string", required: false, description: "Postal code", example: "1700" },
      { key: "country", label: "Country", type: "string", required: false, description: "Country name", example: "Bangladesh" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Warehouse status", example: "active" },
    ],
    sampleData: {
      "Warehouse Name": "Chittagong Port Storage",
      "Warehouse Code": "WH-CTG",
      "Address": "Agrabad Commercial Area",
      "City": "Chittagong",
      "State / Division": "Chittagong",
      "ZIP Code": "4000",
      "Country": "Bangladesh",
      "Status": "active",
    },
  },
  {
    id: "Categories",
    name: "Categories",
    label: "Product Categories",
    description: "Import product categories for item organization.",
    targetModel: "Category",
    permissionKey: "master.categories",
    uniqueIdentifierKeys: ["name", "slug"],
    fields: [
      { key: "name", label: "Category Name", type: "string", required: true, description: "Display name of category", example: "Menswear" },
      { key: "slug", label: "URL Slug", type: "string", required: false, description: "Custom URL slug", example: "menswear" },
      { key: "description", label: "Description", type: "string", required: false, description: "Category description", example: "Men's fashion and apparel" },
      { key: "image", label: "Image URL", type: "string", required: false, description: "Category thumbnail URL", example: "https://example.com/cat.jpg" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Status", example: "active" },
    ],
    sampleData: {
      "Category Name": "Women Footwear",
      "URL Slug": "women-footwear",
      "Description": "Shoes, heels and sandals",
      "Image URL": "https://example.com/footwear.jpg",
      "Status": "active",
    },
  },
  {
    id: "Brands",
    name: "Brands",
    label: "Brands",
    description: "Import brand master data.",
    targetModel: "Brand",
    permissionKey: "master.brands",
    uniqueIdentifierKeys: ["name", "slug"],
    fields: [
      { key: "name", label: "Brand Name", type: "string", required: true, description: "Name of the brand", example: "Nike" },
      { key: "slug", label: "URL Slug", type: "string", required: false, description: "Custom URL slug", example: "nike" },
      { key: "description", label: "Description", type: "string", required: false, description: "Brand details or tagline", example: "Sports and athletic wear" },
      { key: "image", label: "Logo URL", type: "string", required: false, description: "Brand logo URL", example: "https://example.com/nike.png" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Status", example: "active" },
    ],
    sampleData: {
      "Brand Name": "Urban Denim",
      "URL Slug": "urban-denim",
      "Description": "Premium denim jeans and outerwear",
      "Logo URL": "https://example.com/urban.png",
      "Status": "active",
    },
  },
  {
    id: "Units",
    name: "Units",
    label: "Measurement Units",
    description: "Import unit of measurement definitions (e.g. PCS, KG, LTR).",
    targetModel: "Unit",
    permissionKey: "master.units",
    uniqueIdentifierKeys: ["symbol", "details"],
    fields: [
      { key: "name", label: "Unit Details / Name", type: "string", required: true, description: "Full name of unit", example: "Pieces" },
      { key: "code", label: "Unit Symbol / Code", type: "string", required: true, description: "Unique symbol", example: "PCS" },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["active", "inactive"], description: "Status", example: "active" },
    ],
    sampleData: {
      "Unit Details / Name": "Kilogram",
      "Unit Symbol / Code": "KG",
      "Status": "active",
    },
  },
];

/**
 * Get import module configuration by ID
 */
export function getImportModuleConfig(id: string): ImportModuleConfig | undefined {
  return IMPORT_MODULES.find((mod) => mod.id === id || mod.name.toLowerCase() === id.toLowerCase());
}
